<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="DESKTOP-IAQTT8M"><DocLocation><![CDATA[C:\Users\PRASAD\Documents\Unified Functional Testing\SalesForce\Cases]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Cases]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Cases]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Fname&gt; column does not exist.<BR/>Line (13): &quot;Fname=Datatable(&quot;Fname&quot;,Environment.Value(&quot;ActionName&quot;))&quot;. ]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:19]]></Time>
<TimeTick>1591675159</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Failed" Source="Cases" SourceLine="12" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Lname&gt; column does not exist.<BR/>Line (14): &quot;Lname=Datatable(&quot;Lname&quot;,Environment.Value(&quot;ActionName&quot;))&quot;. ]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:22]]></Time>
<TimeTick>1591675162</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Failed" Source="Cases" SourceLine="13" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Email&gt; column does not exist.<BR/>Line (15): &quot;Email=Datatable(&quot;Email&quot;,Environment.Value(&quot;ActionName&quot;))&quot;. ]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:22]]></Time>
<TimeTick>1591675162</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Failed" Source="Cases" SourceLine="14" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Title&gt; column does not exist.<BR/>Line (16): &quot;Title=Datatable(&quot;Title&quot;,Environment.Value(&quot;ActionName&quot;))&quot;. ]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:23]]></Time>
<TimeTick>1591675163</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Failed" Source="Cases" SourceLine="15" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:24]]></Time>
<TimeTick>1591675164</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[abc | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:24]]></Time>
<TimeTick>1591675164</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Cases.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:24]]></Time>
<TimeTick>1591675164</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" Source="Cases" SourceLine="15" >
<Disp><![CDATA[Cases.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Cases.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:24]]></Time>
<TimeTick>1591675164</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Cases" SourceLine="19" >
<Disp><![CDATA[Cases.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" Source="Cases" SourceLine="15" >
<Disp><![CDATA[abc | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" Source="Cases" SourceLine="15" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Cases  ]]></Obj>
<Details ><![CDATA[Click on Cases link]]></Details>
<Time><![CDATA[6/9/2020 - 9:29:39]]></Time>
<TimeTick>1591675179</TimeTick>
<NodeArgs eType="User" icon="9" nRep="19" status="Passed" Source="Cases" SourceLine="21" >
<Disp><![CDATA[Cases  ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:05]]></Time>
<TimeTick>1591675205</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Cases | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:05]]></Time>
<TimeTick>1591675205</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[New.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:05]]></Time>
<TimeTick>1591675205</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="Cases" SourceLine="29" >
<Disp><![CDATA[New.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[New.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:05]]></Time>
<TimeTick>1591675205</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="Cases" SourceLine="31" >
<Disp><![CDATA[New.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="22" Source="Cases" SourceLine="29" >
<Disp><![CDATA[Cases | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" Source="Cases" SourceLine="29" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Cases Creation ]]></Obj>
<Details ><![CDATA[Click on New Cases link]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:05]]></Time>
<TimeTick>1591675205</TimeTick>
<NodeArgs eType="User" icon="9" nRep="27" status="Passed" Source="Cases" SourceLine="33" >
<Disp><![CDATA[Cases Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:15]]></Time>
<TimeTick>1591675215</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[New Contact | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:15]]></Time>
<TimeTick>1591675215</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[New Contact.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:15]]></Time>
<TimeTick>1591675215</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="71" Source="Cases" SourceLine="40" >
<Disp><![CDATA[New Contact.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="70" Source="Cases" SourceLine="40" >
<Disp><![CDATA[New Contact | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="69" Source="Cases" SourceLine="40" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[NewContact Creation ]]></Obj>
<Details ><![CDATA[Salution field is not displayed]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:15]]></Time>
<TimeTick>1591675215</TimeTick>
<NodeArgs eType="User" icon="9" nRep="72" status="Failed" Source="Cases" SourceLine="46" >
<Disp><![CDATA[NewContact Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:36]]></Time>
<TimeTick>1591675236</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[New Contact | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:36]]></Time>
<TimeTick>1591675236</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[First Name]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"First&nbsp;Name"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:36]]></Time>
<TimeTick>1591675236</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[First Name]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>miccommentproperty = <br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV[normalize-space()="First Name"]/INPUT[1]<br>|rows = 0<br>placeholder = First Name<br>Name = WebEdit<br>Max Length = 40<br>Html Id = 143:5351;a<br>default value = <br>DHTML Class = firstName compoundBorderBottom form-element__row input<br>acc_name = <br>]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:36]]></Time>
<TimeTick>1591675236</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="113" status="Warning" nType="Description" Source="Cases" SourceLine="51" >
<Disp><![CDATA[First Name]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="112" status="Failed" nType="Run Error" Source="Cases" SourceLine="51" >
<Disp><![CDATA[First Name]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="111" status="Failed" Source="Cases" SourceLine="51" >
<Disp><![CDATA[New Contact | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="110" status="Failed" Source="Cases" SourceLine="51" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:36]]></Time>
<TimeTick>1591675236</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[New Contact | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:37]]></Time>
<TimeTick>1591675237</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;First Name&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (52): &quot;Browser(&quot;Home | Salesforce&quot;).Page(&quot;New Contact | Salesforce&quot;).WebEdit(&quot;First Name&quot;).Set Fname&quot;. ]]></Details>
<Time><![CDATA[6/9/2020 - 9:30:37]]></Time>
<TimeTick>1591675237</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="116" status="Failed" Source="Cases" SourceLine="51" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[6/9/2020 - 9:31:36]]></Time>
<TimeTick>1591675296</TimeTick>
<NodeArgs eType="General" icon="12" nRep="117" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="115" status="Failed" Source="Cases" SourceLine="51" >
<Disp><![CDATA[New Contact | Salesforce]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act0\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="114" status="Failed" Source="Cases" SourceLine="51" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act0\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[198742]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="6/9/2020 - 9:29:18" eTime="6/9/2020 - 9:31:36" passed="2" failed="7" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Cases Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Cases Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="6/9/2020 - 9:29:16" eTime="6/9/2020 - 9:31:36" passed="2" failed="7" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Cases Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>