<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="DESKTOP-IAQTT8M"><DocLocation><![CDATA[C:\Users\PRASAD\Documents\Unified Functional Testing\SalesForce\Cases]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Cases]]></DName>
<Res><![CDATA[Res9]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Cases]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[6/9/2020 - 16:58:45]]></Time>
<TimeTick>1591702125</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Cases" SourceLine="2" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Description&gt; column does not exist.<BR/>Line (17): &quot;Descrition=Datatable(&quot;Description&quot;,Environment.Value(&quot;ActionName&quot;))&quot;. ]]></Details>
<Time><![CDATA[6/9/2020 - 16:58:45]]></Time>
<TimeTick>1591702125</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="9" status="Failed" Source="Cases" SourceLine="16" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 16:58:51]]></Time>
<TimeTick>1591702131</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[abc | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 16:58:51]]></Time>
<TimeTick>1591702131</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Cases.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/9/2020 - 16:58:51]]></Time>
<TimeTick>1591702131</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="14" Source="Cases" SourceLine="23" >
<Disp><![CDATA[Cases.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Cases.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 16:58:51]]></Time>
<TimeTick>1591702131</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" Source="Cases" SourceLine="25" >
<Disp><![CDATA[Cases.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="13" Source="Cases" SourceLine="23" >
<Disp><![CDATA[abc | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" Source="Cases" SourceLine="23" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Click on  Cases link]]></Obj>
<Details ><![CDATA[Pass]]></Details>
<Time><![CDATA[6/9/2020 - 16:58:59]]></Time>
<TimeTick>1591702139</TimeTick>
<NodeArgs eType="User" icon="10" nRep="18" status="Passed" Source="Cases" SourceLine="29" >
<Disp><![CDATA[Click on  Cases link]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:08]]></Time>
<TimeTick>1591702148</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Cases | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:08]]></Time>
<TimeTick>1591702148</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[New.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:08]]></Time>
<TimeTick>1591702148</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="22" Source="Cases" SourceLine="40" >
<Disp><![CDATA[New.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[New.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:10]]></Time>
<TimeTick>1591702150</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="26" Source="Cases" SourceLine="42" >
<Disp><![CDATA[New.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="21" Source="Cases" SourceLine="40" >
<Disp><![CDATA[Cases | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="20" Source="Cases" SourceLine="40" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Click on Cases link]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:10]]></Time>
<TimeTick>1591702150</TimeTick>
<NodeArgs eType="User" icon="10" nRep="27" status="Passed" Source="Cases" SourceLine="44" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:20]]></Time>
<TimeTick>1591702160</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[New Contact | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:20]]></Time>
<TimeTick>1591702160</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[New Contact.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:20]]></Time>
<TimeTick>1591702160</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="Cases" SourceLine="55" >
<Disp><![CDATA[New Contact.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="57" Source="Cases" SourceLine="55" >
<Disp><![CDATA[New Contact | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="56" Source="Cases" SourceLine="55" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Salution field is not displayed]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:20]]></Time>
<TimeTick>1591702160</TimeTick>
<NodeArgs eType="User" icon="10" nRep="59" status="Failed" Source="Cases" SourceLine="65" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:44]]></Time>
<TimeTick>1591702184</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[New Case | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:44]]></Time>
<TimeTick>1591702184</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA["FirstContact"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:44]]></Time>
<TimeTick>1591702184</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="99" status="Warning" Source="Cases" SourceLine="71" >
<Disp><![CDATA["FirstContact"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["FirstContact"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>xpath=//DIV/DIV[@role="listitem"]/DIV/DIV/DIV/DIV/DIV/DIV/DIV/DIV[@role="listbox"]/DIV/UL[@role="presentation"]/LI[@role="presentation"]/A[@role="option"]/DIV[normalize-space()=.*]/DIV[1]<br>micclass=WebElement<br>html tag=DIV<br>class=primaryLabel slds-truncate slds-lookup__result-text<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1461 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=DIV<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 1415 matches)</SPAN><br>class=primaryLabel slds-truncate slds-lookup__result-text<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>innertext=john dane<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:44]]></Time>
<TimeTick>1591702184</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="100" Source="Cases" SourceLine="71" >
<Disp><![CDATA["FirstContact"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[FirstContact.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 16:59:44]]></Time>
<TimeTick>1591702184</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="101" Source="Cases" SourceLine="71" >
<Disp><![CDATA[FirstContact.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA["FirstContact"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:07]]></Time>
<TimeTick>1591702207</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="132" status="Warning" Source="Cases" SourceLine="72" >
<Disp><![CDATA["FirstContact"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA["FirstContact"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>xpath=//DIV/DIV[@role="listitem"]/DIV/DIV/DIV/DIV/DIV/DIV/DIV/DIV[@role="listbox"]/DIV/UL[@role="presentation"]/LI[@role="presentation"]/A[@role="option"]/DIV[normalize-space()=.*]/DIV[1]<br>micclass=WebElement<br>html tag=DIV<br>class=primaryLabel slds-truncate slds-lookup__result-text<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1461 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=DIV<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 1415 matches)</SPAN><br>class=primaryLabel slds-truncate slds-lookup__result-text<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>innertext=john dane<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:07]]></Time>
<TimeTick>1591702207</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="133" Source="Cases" SourceLine="72" >
<Disp><![CDATA["FirstContact"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="98" status="Warning" Source="Cases" SourceLine="71" >
<Disp><![CDATA[New Case | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="97" status="Warning" Source="Cases" SourceLine="71" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Select the contact as: john dane]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:07]]></Time>
<TimeTick>1591702207</TimeTick>
<NodeArgs eType="User" icon="10" nRep="134" status="Passed" Source="Cases" SourceLine="73" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:13]]></Time>
<TimeTick>1591702213</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[New Case | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:13]]></Time>
<TimeTick>1591702213</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[--None--.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:13]]></Time>
<TimeTick>1591702213</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="139" Source="Cases" SourceLine="78" >
<Disp><![CDATA[--None--.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Phone ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:18]]></Time>
<TimeTick>1591702218</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="142" Source="Cases" SourceLine="83" >
<Disp><![CDATA[[ Phone ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="138" Source="Cases" SourceLine="78" >
<Disp><![CDATA[New Case | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="137" Source="Cases" SourceLine="78" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Select the Case Origin as: Phone]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:18]]></Time>
<TimeTick>1591702218</TimeTick>
<NodeArgs eType="User" icon="10" nRep="143" status="Passed" Source="Cases" SourceLine="84" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:18]]></Time>
<TimeTick>1591702218</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[New Case | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:18]]></Time>
<TimeTick>1591702218</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Subject.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TestSubject"]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:18]]></Time>
<TimeTick>1591702218</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="148" Source="Cases" SourceLine="88" >
<Disp><![CDATA[Subject.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="147" Source="Cases" SourceLine="88" >
<Disp><![CDATA[New Case | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="146" Source="Cases" SourceLine="88" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Enter the subject: TestSubject]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:18]]></Time>
<TimeTick>1591702218</TimeTick>
<NodeArgs eType="User" icon="10" nRep="149" status="Passed" Source="Cases" SourceLine="89" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[New Case | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Description.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="154" Source="Cases" SourceLine="93" >
<Disp><![CDATA[Description.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="153" Source="Cases" SourceLine="93" >
<Disp><![CDATA[New Case | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="152" Source="Cases" SourceLine="93" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Enter the Description: ]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<NodeArgs eType="User" icon="10" nRep="155" status="Passed" Source="Cases" SourceLine="94" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[New Case | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Internal_Commnets.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TestCommentds"]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="160" Source="Cases" SourceLine="98" >
<Disp><![CDATA[Internal_Commnets.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="159" Source="Cases" SourceLine="98" >
<Disp><![CDATA[New Case | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="158" Source="Cases" SourceLine="98" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Enter the Comments: TestCommentds]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<NodeArgs eType="User" icon="10" nRep="161" status="Passed" Source="Cases" SourceLine="99" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[New Case | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[WebMail.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test.TEst1@yopmail.com"]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="166" Source="Cases" SourceLine="103" >
<Disp><![CDATA[WebMail.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[WebCompany.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TestCompany"]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="169" Source="Cases" SourceLine="106" >
<Disp><![CDATA[WebCompany.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="165" Source="Cases" SourceLine="103" >
<Disp><![CDATA[New Case | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="164" Source="Cases" SourceLine="103" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Enter the WebCompany: TestCompany]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:19]]></Time>
<TimeTick>1591702219</TimeTick>
<NodeArgs eType="User" icon="10" nRep="170" status="Passed" Source="Cases" SourceLine="107" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:20]]></Time>
<TimeTick>1591702220</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[New Case | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:20]]></Time>
<TimeTick>1591702220</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:20]]></Time>
<TimeTick>1591702220</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="175" Source="Cases" SourceLine="111" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="174" Source="Cases" SourceLine="111" >
<Disp><![CDATA[New Case | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:20]]></Time>
<TimeTick>1591702220</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="177" Source="Cases" SourceLine="116" >
<Disp><![CDATA[Home | Salesforce.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Cases | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:22]]></Time>
<TimeTick>1591702222</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Casecreated..Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:22]]></Time>
<TimeTick>1591702222</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="184" Source="Cases" SourceLine="119" >
<Disp><![CDATA[Casecreated..Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="183" Source="Cases" SourceLine="119" >
<Disp><![CDATA[Cases | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="173" Source="Cases" SourceLine="111" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>
<Details ><![CDATA[Case added successful: Case 00001013 was created.]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:24]]></Time>
<TimeTick>1591702224</TimeTick>
<NodeArgs eType="User" icon="10" nRep="187" status="Passed" Source="Cases" SourceLine="123" >
<Disp><![CDATA[Account_Cases_Creation ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Home | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:33]]></Time>
<TimeTick>1591702233</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Cases | Salesforce]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:33]]></Time>
<TimeTick>1591702233</TimeTick>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[AccountName.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:33]]></Time>
<TimeTick>1591702233</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="191" Source="Cases" SourceLine="134" >
<Disp><![CDATA[AccountName.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[AccountName.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/9/2020 - 17:00:33]]></Time>
<TimeTick>1591702233</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="194" Source="Cases" SourceLine="135" >
<Disp><![CDATA[AccountName.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="190" Source="Cases" SourceLine="134" >
<Disp><![CDATA[Cases | Salesforce]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="189" Source="Cases" SourceLine="134" >
<Disp><![CDATA[Home | Salesforce]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj ><![CDATA[Account_Cases_Creation ]]></Obj>